---
run:
  # concurrency: 6
  go: "1.23"
  timeout: 2m
  issues-exit-code: 1
  tests: true
linters-settings:
  goheader:
    template-path: ".ci/license/template.txt"
    values:
      regexp:
        company: .*
        copyright-holder: Copyright \(c\) ({{year-range}}) {{company}}\n\n
        copyright-holders: ({{copyright-holder}})+
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf
  goimports:
    local-prefixes: github.com/networkservicemesh/api
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 150
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gosec:
    excludes:
      - G115
  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - appendCombine
      - argOrder
      - badCall
      - badCond
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deprecatedComment
      - docStub
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - flagDeref
      - flagName
      - hexLiteral
      - hugeParam
      - ifElseChain
      - importShadow
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - octalLiteral
      - offBy1
      - paramTypeCombine
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - regexpMust
      - regexpPattern
      - singleCaseSwitch
      - sloppyLen
      - sloppyReassign
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - unlabelStmt
      - unnamedResult
      - unnecessaryBlock
      - underef
      - unlambda
      - unslice
      - valSwap
      - weakCond
      - wrapperFunc
      - yodaStyleExpr
linters:
  disable-all: true
  enable:
    - goheader
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - unused
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: pkg/api/networkservice/mechanism_helpers.go
      linters:
        - interfacer
      text: "can be `github.com/golang/protobuf/proto.Message"
    - path: pkg/api/networkservice/connection_helpers.go
      linters:
        - interfacer
      text: "can be `github.com/golang/protobuf/proto.Message"
    - path: pkg/api/networkservice/path_segment_helpers.go
      linters:
        - interfacer
      text: "can be `github.com/golang/protobuf/proto.Message"
    - path: pkg/api/networkservice/connectioncontext_helpers_test.go
      linters:
        - funlen
      text: "Function 'TestParsePortRange' is too long"
